### ISSUE TITLE
Register for the service 

### ISSUE THREAD

**Issue by Andimoh** [SIU-CS/Finite_Loop-production#10]
<h4>description: </h4>
As a user, I want to be able to register for the service to find parking spots near me.
<h4>Acceptance criteria:</h4> 
1.    Registration view has a place for users to enter needed information.<br>
2.   Confirmation button to confirm registration.<br>
3.   After registering takes them to the map view to look for parking.<br>

<h4>Story source: SRS - FR3<h4>

<h4>Estimate:  8 man-hours  <h4>

**Comment by jake32321** [comment]
Done.  Might need a bit of tweaking.  We will talk about this tomorrow!

**Comment by jake32321** [comment]
Need to fix the issue with the null pointer to an empty UID
