### ISSUE TITLE
Works with Android devices 

### ISSUE THREAD

**Issue by Andimoh** [SIU-CS/Finite_Loop-production#13]
<h4>description: </h4>
As a user, I want to be able to download and use the application to find parking spots.
<h4>Acceptance criteria:</h4> 
1.      The user is able to download and install the app on an Android device.<br>
2.     The user is able to open the run the app and register.<br>
3.     The application allows users to find parking spots that are near them.<br>
4.     Users can pay for their parking through the application.<br>
5.     The amount of time left can be monitored in the app.<br>
<h4>Story source: SRS - FR6<h4>
<h4>Estimate: 2 man-hours<h4>

**Comment by jake32321** [comment]
Obviously done haha 😆
