### ISSUE TITLE
Access personal account information

### ISSUE THREAD

**Issue by Andimoh** [SIU-CS/Finite_Loop-production#17]
<h4>description: </h4>
As a user, I want to be able to access my information to make any necessary changes if needed.
<h4>Acceptance criteria:</h4> 
1.     Account button can be selected from the menu.<br>
2.    Selecting the button takes the user to a view where they can change their information.<br>
3.    The view has a save button to save any changes.<br>
4.    There is a button to delete the account.<br>
5.    Upon deleting the account they are taken to the login/register view.<br>
<h4>Story source:SRS - FR11<h4>
<h4>Estimate: 10 man-hours<h4>

**Comment by jake32321** [comment]
Still needs to be done.  I will work with someone to do this as I put together the firebase stuff.

**Comment by jake32321** [comment]
The starter for the account page is there.  We need to work on the UI and making sure that we have functionality to update the account information and/or delete the user's account. @Andimoh @agnarvaez

**Comment by jake32321** [comment]
@agnarvaez Fixed the issue with deleting the account. See #53 for information.

**Comment by jake32321** [comment]
@Andimoh @agnarvaez @Maha1990 Not all the way there yet but we are close.  Just waiting on @Andimoh's changes.
