### ISSUE TITLE
Store the registration information for users 

### ISSUE THREAD

**Issue by Andimoh** [SIU-CS/Finite_Loop-production#18]
<h4>description: </h4>
As a user, I want to be able to access my information to avoid re-registering every time I want to use the app
<h4>Acceptance criteria:</h4> 
1.     User information is saved to the database.<br>
2.    User can  login and access their information w/o re-registering.<br>
3.    Any change in the user’s information is written to the database.<br>
4.    Account deletion removes the account from the database.<br>
<h4>Story source:SRS - SRS - FR11<h4>
<h4>Estimate: 10 man-hours<h4>

**Comment by jake32321** [comment]
Done.  Might need tweaking.

**Comment by jake32321** [comment]
@Andimoh what progress have you made?

**Comment by Andimoh** [comment]
No progress ... keeps failing

**Comment by jake32321** [comment]
How so? Post an image with the errors please.

**Comment by jake32321** [comment]
@Andimoh Can you post a picture of the issue so I can try to troubleshoot it with you?

**Comment by Andimoh** [comment]
No errors but the App keeps quitting ... might be from my laptop tho not sure

**Comment by Andimoh** [comment]
![screen shot 2017-03-01 at 11 11 42 am](https://cloud.githubusercontent.com/assets/15060826/23471773/0d5f78dc-fe70-11e6-9c0f-3fbc79d21a48.png)

**Comment by jake32321** [comment]
that won't work.  Including it outside of the field validation won't work. Make sure it is within the if statement I mentioned earlier.

**Comment by jake32321** [comment]
The purpose of that statement is field validation to make sure that null references are not made and that we don't feed null data to the database.

**Comment by jake32321** [comment]
@Andimoh

**Comment by Andimoh** [comment]
@jake32321 oh ok

**Comment by jake32321** [comment]
once you make changes let me know.

**Comment by Andimoh** [comment]
ok

**Comment by jake32321** [comment]
@Andimoh any progress?

**Comment by jake32321** [comment]
@Andimoh I made a change to the registration that fixed a huge bug.  Make sure to sync with GH desktop.

**Comment by Andimoh** [comment]
ok

**Comment by jake32321** [comment]
@Andimoh Where are you at with updating account info? Also make sure you're on your branch when making commits.

**Comment by Andimoh** [comment]
i'm on my branch .. i'm going to run it one more now time if that doesn't work .. i really don't know what to do @jake32321

**Comment by Andimoh** [comment]
It's currently on processing give me a sec

**Comment by Andimoh** [comment]
![screen shot 2017-03-01 at 4 42 18 pm](https://cloud.githubusercontent.com/assets/15060826/23484813/32ba7e00-fe9e-11e6-83b1-8863d494825b.png)

**Comment by Andimoh** [comment]
![screen shot 2017-03-01 at 4 42 47 pm](https://cloud.githubusercontent.com/assets/15060826/23484859/5f2b4c62-fe9e-11e6-8c72-2635152399bf.png)
