### ISSUE TITLE
Prompt user’s to use location to find the closest available parking 

### ISSUE THREAD

**Issue by Andimoh** [SIU-CS/Finite_Loop-production#22]
<h4>description: </h4>
As a user, I want to be able to find the closest parking to me to quickly find a spot I can park.
<h4>Acceptance criteria:</h4> 
1.       Upon opening the app for the first time the user will be asked to allow for the app to use their location.<br>
2.    If location services are disabled the app will popup a message prompting the user to turn it on.<br>
3.   Popup will redirect the user to location settings to turn them on.  <br>
4.   Once turned on the app will begin using their location to find parking.<br>
5.   If denied the user can still be given the option to search by location.<br>
<h4>Story source:SRS - SRS - NR1<h4>
<h4>Estimate: 5 man-hours<h4>

**Comment by jake32321** [comment]
This needs to be edited.  I don't believe that we need to have #5 in the criteria.
