### ISSUE TITLE
Application can be used in various locations 

### ISSUE THREAD

**Issue by Andimoh** [SIU-CS/Finite_Loop-production#24]
<h4>description: </h4>
As a user, I want to be able to use this application wherever I go to find available parking when I need it.
<h4>Acceptance criteria:</h4> 
1.    Application uses GPS to find the user's location to find the closest parking to them.<br>
2.    Produces a popup message that says no parking has been found nearby if none are found.<br>
3.   Map in the main view of the application updates with the parking locations nearby.<br>
4.   Ability to select a parking area to find available spots.<br>
<h4>Story source:SRS - SRS - NR3<h4>
<h4>Estimate: 15 man-hours<h4>

**Comment by jake32321** [comment]
Still needs to be done.  I will probably work on this.
