### ISSUE TITLE
About the application page

### ISSUE THREAD

**Issue by Andimoh** [SIU-CS/Finite_Loop-production#27]
<h4>description: </h4>
As a user, I want to be able to know who I can contact for assistance or report a bug if there's is one.
<h4>Acceptance criteria:</h4> 
1.     The main view of the application will have a button the user can select for information.<br>
2.    The view will open and will contain the current version and contact information for the team.<br>
3.    Closing this view will take the user back to the main view of the application.<br>
<h4>Story source:SRS - SRS - NR5<h4>
<h4>Estimate: 2 man-hours<h4>

**Comment by jake32321** [comment]
Still needs to be done.  I will assign someone to do this.
